namespace: sparta
name: collector
version: 0.0.1
readme: README.md
authors:
- Kat Morgan <usrbinkat@codectl.io>
description: 'CodeSparta artifact collector automation'
tags:
  - iac
  - upi
  - openshift
  - disconnected
  - airgap
  - ocp
dependencies:
  "containers.podman": ">=1.4.3"
license:
- GPL-2.0-or-later
repository: http://github.com/codesparta/collector
issues: http://github.com/codesparta/collector
documentation: http://codectl.io
homepage: http://codectl.io
build_ignore:
  - ci
  - tests/output
  - build_artifact
  - "*.tar.gz"
  - ".gitignore"
  - ".history"
  - ".vscode"
  - ".idea"
  - ".github"
  - contrib
  - importer_result.json
